$ npins get-path broken
error:
       … while calling anonymous lambda
         at «string»:1:1:
            1| {pin, path}: ((/*
             | ^
            2|   This file is provided under the MIT licence:

       … while evaluating the attribute 'broken.outPath'
         at «string»:133:15:
          132|     in
          133|     spec // { outPath = mayOverride name path; };
             |               ^
          134|

       … from call site
         at «string»:133:25:
          132|     in
          133|     spec // { outPath = mayOverride name path; };
             |                         ^
          134|

       … while calling 'mayOverride'
         at «string»:37:11:
           36|   mayOverride =
           37|     name: path:
             |           ^
           38|     let

       … while evaluating path
         at «string»:44:7:
           43|     if ersatz == "" then
           44|       path
             |       ^
           45|     else

       … from call site
         at «string»:127:11:
          126|         else if spec.type == "Url" || spec.type == "MutableUrl" then
          127|           mkUrlSource fetchers spec
             |           ^
          128|         else if spec.type == "Container" then

       … while calling 'mkUrlSource'
         at «string»:219:5:
          218|     }:
          219|     {
             |     ^
          220|       url,

       … from call site
         at «string»:225:5:
          224|     }:
          225|     (if unpack then fetchTarball else fetchurl) {
             |     ^
          226|       inherit url;

       … while calling 'fetchurl'
         at «string»:69:15:
           68|             fetchurl =
           69|               {
             |               ^
           70|                 url,

       … while calling the 'fetchurl' builtin
         at «string»:73:15:
           72|               }:
           73|               builtins.fetchurl {
             |               ^
           74|                 name = "source";

       error: hash mismatch in file downloaded from 'http://localhost/testTarball':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
         got:       sha256-tarballAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
Error: Could not evaluate pin

Caused by:
    Failed to eval pin: 'broken'
    
