$ npins get-path hello-world
error:
       … while calling anonymous lambda
         at «string»:1:1:
            1| {pin, path}: ((/*
             | ^
            2|   This file is provided under the MIT licence:

       … while evaluating the attribute 'hello-world.outPath'
         at «string»:133:15:
          132|     in
          133|     spec // { outPath = mayOverride name path; };
             |               ^
          134|

       … from call site
         at «string»:133:25:
          132|     in
          133|     spec // { outPath = mayOverride name path; };
             |                         ^
          134|

       … while calling 'mayOverride'
         at «string»:37:11:
           36|   mayOverride =
           37|     name: path:
             |           ^
           38|     let

       … while evaluating path
         at «string»:44:7:
           43|     if ersatz == "" then
           44|       path
             |       ^
           45|     else

       … from call site
         at «string»:129:11:
          128|         else if spec.type == "Container" then
          129|           mkContainerSource pkgs spec
             |           ^
          130|         else

       … while calling 'mkContainerSource'
         at «string»:232:5:
          231|     pkgs:
          232|     {
             |     ^
          233|       image_name,

       … caused by explicit throw
         at «string»:240:7:
          239|     if pkgs == null then
          240|       builtins.throw "container sources require passing in a Nixpkgs value: https://github.com/andir/npins/blob/master/README.md#using-the-nixpkgs-fetchers"
             |       ^
          241|     else

       error: container sources require passing in a Nixpkgs value: https://github.com/andir/npins/blob/master/README.md#using-the-nixpkgs-fetchers
Error: Could not evaluate pin

Caused by:
    Failed to eval pin: 'hello-world'
    
