$ npins update --max-concurrent-downloads 1
[channel-tarball] Changes:
-    url: https://releases.nixos.org/nixos/outdated/nixexprs.tar.xz
+    url: https://releases.nixos.org/nixos/unstable/nixos-26.11pre123456.abcdef/nixexprs.tar.xz
[dependency] Changes:
-    version: 0.1
+    version: v0.2
[forgejo-branch] Changes:
-    revision: 0000000000000000000000000000000000000000
+    revision: 55af235fa333dbcceb6f9f8501e70123fdd5f316
[forgejo-main-1] No Changes
[forgejo-main-2] No Changes
[forgejo-main-3] No Changes
[forgejo-main-4] No Changes
[forgejo-release] Changes:
-    version: 0.1
+    version: v0.2
[generic-repo] Changes:
-    revision: 0000000000000000000000000000000000000000
+    revision: 55af235fa333dbcceb6f9f8501e70123fdd5f316
[main-repo-1] No Changes
[main-repo-2] No Changes
[main-repo-3] No Changes
[main-repo-4] No Changes
[nixos-unstable] Changes:
-    url: https://releases.nixos.org/nixos/outdated/nixexprs.tar.xz
+    url: https://releases.nixos.org/nixos/unstable/nixos-26.11pre123456.abcdef/nixexprs.tar.xz
[submoduled-repo] No Changes
[submoduled-repo-2] No Changes
[tagged-repo] Changes:
-    version: 0.1
+    version: v0.2
-    revision: 0000000000000000000000000000000000000000
+    revision: 55af235fa333dbcceb6f9f8501e70123fdd5f316
[test-tarball] No Changes
[test-tarball-mutable] Changes:
-    url: http://localhost/outdated
+    url: http://localhost/testTarball
[test-url] No Changes
[test-url-mutable] Changes:
-    url: http://localhost/outdated
+    url: http://localhost/testTarball
[untagged-repo] Changes:
-    revision: 0000000000000000000000000000000000000000
+    revision: 81289a3c12d4f528d27794b9e47f4ff5cf534a88
[INFO ] Update successful.
