name: "test"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-26-intel
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: samueldr/lix-gha-installer-action@8dc19fbd6451fa106a68ecb2dafeeeb90dff3a29 # latest @ 2025-02-28
      - name: Build
        run: nix-build
      - name: Cargo Build Lib
        run: nix-shell --run "cargo build -p libnpins"
      - name: Cargo Build CLI
        run: nix-shell --run "cargo build -p npins"
      - name: Run pre-commit hooks
        run: nix-shell --run "pre-commit run --all"
      - name: Cargo test
        run: nix-shell --run "cargo test --all"
      - name: Test dev shell
        # Simple check that the pins in the current repository are still working.
        # Importantly, this will fail on any version mismatch, indicating that versions need to be upgraded.
        run: nix-shell --run "npins show"
      - name: Run smoke test
        run: nix-shell --run "bash ./.github/workflows/smoke-test.sh"
      - name: Run integration tests
        if: ${{ runner.os == 'Linux' }}
        run: nix-build -A meta.tests
