name: "test"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Build
        run: nix-build
      - name: Run pre-commit hooks
        run: nix-shell --run "pre-commit run --all"
      - name: Run smoke test
        run: nix-shell --run "bash ./.github/workflows/smoke-test.sh"
      - name: Run integration tests
        run: nix-build -A meta.tests
